name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        . venv/bin/activate
        python manage.py test

    - name: Lint with flake8 and black
      run: |
        . venv/bin/activate
        flake8 . && black --check .
